import React, { useState } from "react";
import {
  Award,
  CheckCircle2,
  Download,
  ExternalLink,
  ShieldCheck,
  X,
} from "lucide-react";
import { tr } from "../i18n/index.js";
import {
  PageHeading,
  Pill,
  Progress,
  SystemCard,
} from "../components/common/index.js";
import { generateClientPdfBlob } from "../utils/pdfGenerator.js";
import {
  API_BASE_URL,
  API_TOKEN_KEY,
  getCertificateDownloadUrl,
  getCertificateVerificationUrl,
  apiDownloadCertificateBlob,
} from "../services/api/client.js";

export default function CertificatesPage({ lang, data = {}, onNavigate, apiToken }) {
  const [verifyingCert, setVerifyingCert] = useState(null);
  const [copiedLink, setCopiedLink] = useState(false);
  const [downloadingCert, setDownloadingCert] = useState(false);

  const certificates = data?.certificates || [];
  const earned = certificates.filter((c) => c.status === "Active").length;
  const inProgress = certificates.filter((c) => c.status === "In Progress").length;
  const expiring = certificates.filter((c) => c.status === "Expiring Soon").length;

  const handleCopyLink = (cert) => {
    const certId = cert.id || "CERT-IN-2026-NSSTA-9041";
    const verificationUrl = getCertificateVerificationUrl(certId);
    navigator.clipboard?.writeText(verificationUrl);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2200);
  };

  const handleDownloadCert = async (cert) => {
    if (!cert) return;
    setDownloadingCert(true);
    const certId = cert.id || "CERT-NSSTA-2026";
    const recipientName =
      data?.profile?.name || data?.user?.name || "Official Learner";
    const cleanTitle = (cert.title || "Accreditation").replace(
      /[^a-zA-Z0-9_-]/g,
      "_"
    );
    const filename = `CERTIFICATE_${cleanTitle}.pdf`;

    try {
      const token = apiToken || localStorage.getItem(API_TOKEN_KEY) || "";
      const blob = await apiDownloadCertificateBlob(certId, {
        token,
        name: recipientName,
        title: cert.title || "",
      });
      const blobUrl = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = blobUrl;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(blobUrl);
    } catch (err) {
      console.warn(
        "Backend certificate download fallback to client generator:",
        err
      );
      const blob = generateClientPdfBlob(
        `STATSKILL AI CERTIFICATE: ${cert.title || "Statistical Competency"}`,
        `StatSkill AI Learning Platform · Credential ${certId}`,
        [
          "STATSKILL AI COMPETENCY CERTIFICATION",
          "Digital Statistical Capability Development Platform",
          "Aligned with National Statistical System (FRAC) Competency Standards",
          "--------------------------------------------------------------------------------",
          "COMPETENCY ACHIEVEMENT CERTIFICATE",
          "--------------------------------------------------------------------------------",
          `This is to certify that: ${recipientName}`,
          "has successfully demonstrated required proficiency in:",
          `>> ${(cert.title || "Statistical Competency").toUpperCase()}`,
          "",
          "Accreditation Benchmark: FRAC Level 4 (National Statistical Framework)",
          `Credential Identifier: ${certId}`,
          "Issuing System: StatSkill AI Platform Engine",
          "Verification Standard: StatSkill Continuous Assessment & Evaluation",
          `Issued Date: ${cert.issued || "15 January 2025"}        Valid Until: ${cert.expires || "14 January 2028"}`,
          "Status: Active Platform Credential",
          "Verification URL: Available via StatSkill Public Credential Verification API",
          "--------------------------------------------------------------------------------",
          "This certificate is generated by StatSkill AI to document competency mastery.",
          "StatSkill AI Adaptive Learning Architecture",
        ]
      );
      const blobUrl = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = blobUrl;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(blobUrl);
    } finally {
      setTimeout(() => setDownloadingCert(false), 500);
    }
  };

  return (
    <div className="stack">
      <PageHeading
        kicker={tr(lang, "credentialLedger").toUpperCase()}
        title={tr(lang, "certificates")}
        subtitle={tr(lang, "visualSummary")}
      />
      <div className="summary-grid three">
        <SystemCard className="summary-card">
          <span>{tr(lang, "certificatesEarned").toUpperCase()}</span>
          <strong className="green">{earned}</strong>
        </SystemCard>
        <SystemCard className="summary-card">
          <span>{tr(lang, "inProgress").toUpperCase()}</span>
          <strong className="cyan">{inProgress}</strong>
        </SystemCard>
        <SystemCard className="summary-card">
          <span>{tr(lang, "expiringSoon").toUpperCase()}</span>
          <strong className="amber">{expiring}</strong>
        </SystemCard>
      </div>

      <div className="certificate-grid">
        {certificates.map((c) => (
          <SystemCard className="certificate-card" key={c.id || c.title}>
            <div className="certificate-top">
              <div className={`mini-icon ${c.color || "blue"}`}>
                <Award size={17} />
              </div>
              <Pill
                tone={
                  c.color === "green"
                    ? "strong"
                    : c.color === "amber"
                    ? "warning"
                    : "active"
                }
              >
                {c.status}
              </Pill>
            </div>
            <h2>{c.title}</h2>
            <p>{c.issuer}</p>
            {c.progress ? (
              <>
                <Progress value={c.progress} color="cyan" />
                <div className="stat-meta">{c.progress}% complete</div>
              </>
            ) : (
              <div className="certificate-meta">
                <span>
                  Issued<strong>{c.issued}</strong>
                </span>
                <span>
                  Expires<strong>{c.expires}</strong>
                </span>
              </div>
            )}
            <button
              className="secondary-btn"
              onClick={() =>
                c.progress
                  ? onNavigate && onNavigate("Learning Path")
                  : setVerifyingCert(c)
              }
              title={
                c.progress
                  ? "Continue track in Learning Path"
                  : "Verify official credentials"
              }
            >
              <ShieldCheck size={14} />{" "}
              {c.progress ? tr(lang, "continueTrack") : tr(lang, "verifyCredential")}
            </button>
          </SystemCard>
        ))}
      </div>

      {verifyingCert && (
        <div
          className="app-modal-overlay"
          onClick={() => setVerifyingCert(null)}
          role="dialog"
          aria-modal="true"
        >
          <div className="app-modal-dialog" onClick={(e) => e.stopPropagation()}>
            <div className="app-modal-header">
              <div>
                <div className="system-label" style={{ color: "#166534" }}>
                  {tr(lang, "verifiedCertificate").toUpperCase()}
                </div>
                <h3>{verifyingCert.title}</h3>
                <p>
                  {verifyingCert.issuer ||
                    "StatSkill AI Competency Certification Engine"}
                </p>
              </div>
              <button
                className="icon-btn"
                onClick={() => setVerifyingCert(null)}
                aria-label="Close"
              >
                <X size={16} />
              </button>
            </div>
            <div className="app-modal-body">
              <div className="credential-seal-banner">
                <div className="credential-seal-icon">
                  <ShieldCheck size={28} />
                </div>
                <div className="credential-seal-text">
                  <strong>StatSkill AI Platform Credential Verification</strong>
                  <span>
                    Authenticated achievement record based on completed assessments and verified learning milestones
                  </span>
                </div>
              </div>

              <div className="credential-meta-grid">
                <div className="credential-meta-item">
                  <span>Recipient Name</span>
                  <strong>
                    {data?.profile?.name || data?.user?.name || "Official Learner"}
                  </strong>
                </div>
                <div className="credential-meta-item">
                  <span>Credential ID</span>
                  <strong>
                    {verifyingCert.id || "CERT-IN-2026-NSSTA-9041"}
                  </strong>
                </div>
                <div className="credential-meta-item">
                  <span>Issuing Platform</span>
                  <strong>StatSkill AI</strong>
                </div>
                <div className="credential-meta-item">
                  <span>Competency Framework</span>
                  <strong>FRAC Level 4 Statistical Competency</strong>
                </div>
                <div className="credential-meta-item">
                  <span>Date Issued</span>
                  <strong>{verifyingCert.issued || "15 Jan 2025"}</strong>
                </div>
                <div className="credential-meta-item">
                  <span>Valid Until</span>
                  <strong>{verifyingCert.expires || "14 Jan 2028"}</strong>
                </div>
              </div>

              <div className="credential-hash-box">
                <span>Cryptographic Verification Fingerprint (SHA-256)</span>
                <code>
                  {verifyingCert.hash || "sha256:8f4b23c91d8e09f5a11c47be389a02d4e8c1b970f5e1289"}
                </code>
              </div>
            </div>
            <div className="app-modal-footer">
              <button
                className="secondary-btn"
                onClick={() => handleCopyLink(verifyingCert)}
              >
                {copiedLink ? (
                  <>
                    <CheckCircle2 size={14} color="#059669" /> Link Copied!
                  </>
                ) : (
                  <>
                    <ExternalLink size={14} /> {tr(lang, "copyVerificationLink")}
                  </>
                )}
              </button>
              <button
                className="primary-btn"
                onClick={() => handleDownloadCert(verifyingCert)}
                disabled={downloadingCert}
              >
                <Download size={14} />{" "}
                {downloadingCert
                  ? "Generating PDF..."
                  : tr(lang, "downloadOfficialCert")}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
